language: python
dist: xenial
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
install:
  - pip install codecov
  - pip install -r requirements-dev.txt
  - pip install .
script:
  - flake8 --statistics tests rna_cd
  - coverage run --source=rna_cd -m py.test -v tests
  - coverage xml
  - coverage report -m
after_success:
  - codecov
