language: python
matrix:
  include:
    - python: "3.6"
      dist: xenial
    - python: "3.7"
      dist: xenial
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
script:
  - flake8 --statistics tests rna_cd
  - py.test -v --cov=rna_cd --cov-report=term-missing tests
